"""Output writers (tenderpack/render.py): file contents, Excel structure, the one-page A3 and
byte-identical output across directories, processes and time."""
from __future__ import annotations

import csv
import io
import json
import os
import subprocess
import sys
import time
import unicodedata
import zipfile
from pathlib import Path

import openpyxl
import pymupdf
import pytest

from tenderpack.render import (A3OverflowError, FIXED_TIME, A3_SCALE_LOW, status_fill, write_a1, write_a3_pdf,
                               write_csv_json)

ROOT = Path(__file__).resolve().parents[1]
AR = "يؤدي إلى استبعاد العرض"


def _col(key: str, header: str, width: int = 12) -> dict:
    return {"key": key, "header": header, "width": width}


def a1_input() -> dict:
    return {
        "title": "A1 Obligations and compliance register",
        "notice": "DRAFT - interpretations proposed by the assistant, not reviewed; image readings pending",
        "stages": ["BASE", "ADD-01", "ADD-02"],
        "validated_stage": "ADD-02",
        "working_stage": None,
        "columns": [_col("id", "ID", 16), _col("text", "Verbatim source text", 60), _col("evidence", "Evidence needed", 30),
                    _col("status:BASE", "status:BASE"), _col("status:ADD-01", "status:ADD-01"),
                    _col("status:ADD-02", "status:ADD-02"), _col("pass_fail", "Pass/fail", 8),
                    _col("weight", "Weight", 8), _col("review_status", "Review", 20)],
        "rows": [
            {"id": "VOL-I-8.6-01", "text": "Local Content Certificate, not less than 30%",
             "evidence": ["certificate", "ratio calculation"], "status:BASE": "ACTIVE",
             "status:ADD-01": "DELETED (by ADD-01/4.1)", "status:ADD-02": "REINSTATED-AMENDED",
             "pass_fail": True, "weight": None, "review_status": "Pending human review"},
            {"id": "VOL-IV-p6-r1", "text": AR, "evidence": [], "status:BASE": "ACTIVE",
             "status:ADD-01": "AMENDED", "status:ADD-02": "AMENDED STALE", "pass_fail": False,
             "weight": 0.35, "review_status": "approved"},
            {"id": "ADD-02-7-01", "text": "=Form 4-G is not a formula", "evidence": ["Form 4-G"],
             "status:BASE": "NOT ISSUED", "status:ADD-01": "NOT ISSUED", "status:ADD-02": "NEW",
             "pass_fail": True, "weight": 3, "review_status": None},
        ],
        "sheets": {
            "Dates": {"columns": [_col("anchor", "Anchor"), _col("date", "Date")],
                      "rows": [{"anchor": "PDD", "date": "2026-11-26"}, {"anchor": "Clarifications", "date": "2026-11-05"}]},
            "Issues": {"columns": [_col("id", "ID"), _col("text", "Issue", 50), _col("owner", "Owner")],
                       "rows": [{"id": "I-01", "text": "Competent authority not named", "owner": "Bid manager"}]},
        },
    }


def a2_input() -> dict:
    return {"columns": [_col("op", "Operation"), _col("rows", "Rows moved"), _col("note", "Note", 40)],
            "rows": [{"op": "ADD-01/4.1 delete", "rows": ["VOL-I-8.6-01"], "note": AR},
                     {"op": "ADD-02/9.1 reinstate", "rows": ["VOL-I-8.6-01", "VOL-I-9.1-03"], "note": None}]}


def a3_input(n_items: int = 3) -> dict:
    items = [{"id": "VOL-I-8.6-01", "text": "Submit a Local Content Certificate (not less than 35%).",
              "consequence": "Failure to submit the certificate shall render the Proposal non-responsive.",
              "source": "ADD-02 §9.1 p3", "confidence": "high", "flags": ["REINSTATED-AMENDED"]},
             {"id": "VOL-IV-p6-r1", "text": AR, "consequence": AR, "source": "VOL-IV p6 (image)",
              "confidence": "medium", "flags": ["image reading PENDING review"]},
             {"id": "VOL-I-9.2-01", "text": "Page limit 150 (R&D <annexes> count).", "consequence": "",
              "source": "ADD-02 §2.1 p1", "confidence": "medium", "flags": []}]
    items += [{**items[0], "id": f"X-{i:03d}"} for i in range(n_items - len(items))]
    return {
        "title": "A3 What would disqualify us",
        "subtitle": "Validated state: ADD-02 (22 Oct 2026) - DRAFT",
        "banner": "DRAFT - interpretations proposed by the assistant, not reviewed",
        "sections": [{"heading": "Rejection stated in the documents", "note": "Explicit document wording only.",
                      "items": items[:n_items]},
                     {"heading": "Mandatory, no stated consequence", "note": "", "items": []}],
        "unresolved": {"heading": "Could not resolve", "items": [
            {"id": "U-01", "text": "Competent authority not named in the pack.", "owner": "Bid manager"}]},
        "footer": "Generated by tenderpack from the A1 register. Page 1 of 1.",
    }


def write_all(out: Path) -> list[Path]:
    """Every writer once; also run in a subprocess by the determinism test."""
    paths = write_a1(a1_input(), out / "a1")
    paths += write_csv_json(a2_input(), out / "a2", "a2_changes")
    write_a3_pdf(a3_input(), out / "a3" / "a3.pdf")
    return paths + [out / "a3" / "a3.pdf"]


# ------------------------------------------------------------------ A1

def test_a1_files_csv_and_json(tmp_path):
    a1 = a1_input()
    paths = write_a1(a1, tmp_path)
    assert [p.name for p in paths] == ["a1.json", "a1.csv", "a1.xlsx"] and all(p.is_file() for p in paths)
    assert json.loads(paths[0].read_text(encoding="utf-8")) == a1

    raw = paths[1].read_bytes()
    assert raw.startswith(b"\xef\xbb\xbf")                      # BOM, so Excel reads Arabic
    assert raw.count(b"\r\n") == 4 and b"\n" not in raw.replace(b"\r\n", b"")
    rows = list(csv.reader(io.StringIO(raw.decode("utf-8-sig"), newline="")))
    assert rows[0] == [c["header"] for c in a1["columns"]]
    assert rows[1] == ["VOL-I-8.6-01", "Local Content Certificate, not less than 30%",
                       "certificate; ratio calculation", "ACTIVE", "DELETED (by ADD-01/4.1)",
                       "REINSTATED-AMENDED", "TRUE", "", "Pending human review"]
    assert rows[2][1] == AR and rows[2][2] == "" and rows[2][6:8] == ["FALSE", "0.35"]
    assert rows[3][1] == "=Form 4-G is not a formula" and rows[3][7] == "3" and rows[3][8] == ""


def test_a1_xlsx_structure_and_styles(tmp_path):
    a1 = a1_input()
    wb = openpyxl.load_workbook(write_a1(a1, tmp_path)[2])
    assert wb.sheetnames == ["A1 register", "Dates", "Issues"]
    ws = wb["A1 register"]
    assert ws["A1"].value == a1["title"] and ws["A1"].font.b
    assert ws["A2"].value == a1["notice"] and ws["A2"].font.i
    assert ws.freeze_panes == "A5" and ws.auto_filter.ref == "A4:I7"
    assert [c.value for c in ws[4]] == [c["header"] for c in a1["columns"]] and all(c.font.b for c in ws[4])
    assert ws.column_dimensions["B"].width == 60 and ws.column_dimensions["A"].width == 16
    assert ws["B5"].alignment.wrap_text and ws["B5"].alignment.vertical == "top"

    def fill(ref):
        c = ws[ref]
        return c.fill.fgColor.rgb[-6:] if c.fill.fill_type == "solid" else None
    # rows 5-7, status columns D-F
    assert [fill(r) for r in ("D5", "E5", "F5")] == [None, "D9D9D9", "E2EFDA"]
    assert [fill(r) for r in ("D6", "E6", "F6")] == [None, "FFF2CC", "FCE4D6"]
    assert [fill(r) for r in ("D7", "E7", "F7")] == ["F2F2F2", "F2F2F2", "E2EFDA"]
    assert fill("A5") is None and fill("I5") is None
    assert ws["I5"].font.i and not ws["I6"].font.i            # "pending" in a status-like column
    assert ws["B6"].value == AR                                 # Arabic as given, not reordered
    assert ws["C5"].value == "certificate; ratio calculation" and ws["C6"].value is None
    assert ws["G5"].value is True and ws["H6"].value == 0.35 and ws["H5"].value is None
    assert ws["B7"].value == "=Form 4-G is not a formula" and ws["B7"].data_type == "s"

    for name, n_rows in (("Dates", 2), ("Issues", 1)):
        sh, spec = wb[name], a1["sheets"][name]
        assert sh.freeze_panes == "A2" and sh.auto_filter.ref == f"A1:{'BC'[len(spec['columns']) - 2]}{1 + n_rows}"
        assert [c.value for c in sh[1]] == [c["header"] for c in spec["columns"]] and all(c.font.b for c in sh[1])
    assert wb["Issues"]["B1"].value == "Issue" and wb["Issues"].column_dimensions["B"].width == 50


def test_a1_xlsx_has_no_save_time(tmp_path):
    path = write_a1(a1_input(), tmp_path)[2]
    wb = openpyxl.load_workbook(path)
    assert wb.properties.created == FIXED_TIME and wb.properties.modified == FIXED_TIME
    assert wb.properties.creator == wb.properties.lastModifiedBy == "tenderpack"
    with zipfile.ZipFile(path) as z:
        infos = z.infolist()
    assert infos[0].filename == "[Content_Types].xml"
    assert [i.filename for i in infos[1:]] == sorted(i.filename for i in infos[1:])
    assert {i.date_time for i in infos} == {(1980, 1, 1, 0, 0, 0)}
    assert {i.compress_type for i in infos} == {zipfile.ZIP_DEFLATED}


def test_status_fill_rules():
    assert status_fill("DELETED (by ADD-01/4.1)") == "D9D9D9"
    assert status_fill("STALE") == status_fill("AMENDED STALE") == status_fill("REINSTATED (STALE)") == "FCE4D6"
    assert status_fill("NEW") == status_fill("REINSTATED-AMENDED") == "E2EFDA"
    assert status_fill("AMENDED by ADD-02/3.1") == "FFF2CC"
    assert status_fill("NOT ISSUED") == "F2F2F2"
    assert status_fill("ACTIVE") is None and status_fill(None) is None and status_fill("") is None


def test_unsupported_values_and_duplicate_keys_are_refused(tmp_path):
    bad = {"columns": [_col("a", "A")], "rows": [{"a": {"x", "y"}}]}
    with pytest.raises(TypeError):
        write_csv_json(bad, tmp_path, "bad")
    with pytest.raises(ValueError, match="duplicate"):
        write_csv_json({"columns": [_col("a", "A"), _col("a", "B")], "rows": []}, tmp_path, "dup")
    assert not list(tmp_path.iterdir())                         # nothing written on failure


# ------------------------------------------------------------------ A2 / A5 tables

def test_csv_json_generic(tmp_path):
    table = a2_input()
    paths = write_csv_json(table, tmp_path / "out", "a2_changes")
    assert [p.name for p in paths] == ["a2_changes.csv", "a2_changes.json"]
    assert json.loads(paths[1].read_text(encoding="utf-8")) == table
    raw = paths[0].read_bytes()
    assert raw.startswith(b"\xef\xbb\xbf") and raw.endswith(b"\r\n")
    rows = list(csv.reader(io.StringIO(raw.decode("utf-8-sig"), newline="")))
    assert rows == [["Operation", "Rows moved", "Note"], ["ADD-01/4.1 delete", "VOL-I-8.6-01", AR],
                    ["ADD-02/9.1 reinstate", "VOL-I-8.6-01; VOL-I-9.1-03", ""]]


# ------------------------------------------------------------------ A3

def test_a3_one_page_with_key_texts(tmp_path):
    a3 = a3_input()
    path = tmp_path / "a3.pdf"
    info = write_a3_pdf(a3, path)
    assert info["pages"] == 1 and A3_SCALE_LOW <= info["scale"] <= 1 and info["spare_pt"] >= 0
    doc = pymupdf.open(path)
    assert doc.page_count == 1
    page = doc[0]
    assert (round(page.rect.width), round(page.rect.height)) == (595, 842)
    # compared after NFKC without whitespace: MuPDF extracts the "fi" ligature and wraps at hyphens
    def flat(s: str) -> str:
        return "".join(unicodedata.normalize("NFKC", s).split())
    text = flat(page.get_text())
    for key in (a3["title"], a3["subtitle"], a3["banner"], "Rejection stated in the documents",
                "Explicit document wording only.", "VOL-I-8.6-01", "VOL-IV-p6-r1",
                "“Failure to submit the certificate shall render the Proposal non-responsive.”",
                "ADD-02 §9.1 p3", "confidence high", "REINSTATED-AMENDED", "image reading PENDING review",
                "R&D <annexes>", "Mandatory, no stated consequence", "None.", "Could not resolve", "U-01",
                "Competent authority not named in the pack.", "owner: Bid manager", a3["footer"]):
        assert flat(key) in text, key
    meta = doc.metadata
    assert meta["producer"] == "tenderpack" and meta["creationDate"] == meta["modDate"] == "D:20261001000000Z"
    assert b"/ID" not in path.read_bytes()


def test_a3_arabic_is_shaped_and_right_to_left(tmp_path):
    path = tmp_path / "a3.pdf"
    write_a3_pdf(a3_input(), path)
    page = pymupdf.open(path)[0]
    assert any("Noto Naskh Arabic" in f[3] for f in page.get_fonts())   # bundled with PyMuPDF
    # MuPDF extracts shaped Arabic as presentation forms (shaping happened); NFKC gives the letters
    words = [(w[0], w[1], unicodedata.normalize("NFKC", w[4])) for w in page.get_text("words")]
    first = [(x, y) for x, y, t in words if t == "يؤدي"]
    later = [(x, y) for x, y, t in words if t == "استبعاد"]
    assert len(first) == len(later) == 2                        # text and consequence of VOL-IV-p6-r1
    for (x1, y1), (x2, y2) in zip(sorted(first), sorted(later)):
        assert abs(y1 - y2) < 1 and x1 > x2                     # first word is to the right


def test_a3_overflow_raises_and_writes_nothing(tmp_path):
    path = tmp_path / "a3.pdf"
    with pytest.raises(A3OverflowError, match="one A4 page"):
        write_a3_pdf(a3_input(300), path)
    assert not path.exists()


# ------------------------------------------------------------------ determinism

def test_two_writes_are_byte_identical(tmp_path):
    """One write here, one in another process (other hash seed) at least 2 s later (zip times have
    2 s resolution), into another directory: every file must be identical."""
    start = time.monotonic()
    a = write_all(tmp_path / "a")
    time.sleep(max(0.0, 2.1 - (time.monotonic() - start)))
    code = ("import sys; from pathlib import Path; sys.path[:0] = [sys.argv[1], sys.argv[1] + '/tests']; "
            "import test_render; test_render.write_all(Path(sys.argv[2]))")
    env = {**os.environ, "PYTHONHASHSEED": "12345"}
    subprocess.run([sys.executable, "-c", code, str(ROOT), str(tmp_path / "b")], check=True, env=env, cwd=tmp_path)
    b = [tmp_path / "b" / p.relative_to(tmp_path / "a") for p in a]
    assert sorted(p.suffix for p in a) == [".csv", ".csv", ".json", ".json", ".pdf", ".xlsx"]
    for pa, pb in zip(a, b):
        assert pa.read_bytes() == pb.read_bytes(), pa.name
